### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#24] opened 2015-10-04 19:26 UTC
I remembered that there was this note by Southey where he explained the word “beata”. I changed the source text so as the note was inside an `<anchor type="add"/>` so it would get highlighted in the chart, but this is not the same type of addition.
So, this is just a reminder that we haven't decided how we'll deal with notes.

**Comment by ebeshero** [comment] 2015-10-04 23:28
I've been coding <note> elements exactly where they are signalled for inclusion in Southey's text. When you say you've moved the note so it's _inside_, I imagine you're referring to moving it inside an `<anchor>` element that Stacey has applied, right?  So do we just need to make a decision that we want Southey's notes to sit as a _kind_ of addition inside the `<anchor>` element? Is there any reason we should not do this?

@setriplette 
@HelenaSabel

**Comment by ebeshero** [comment] 2015-10-04 23:30
@HelenaSabel Sorry about that--I realized your comment wasn't showing the `<anchor>` element because you needed to put it inside tick marks for a block of code! I just fixed it so we can fully see it. And yes, I see that _is_ what you're talking about. ;-)

**Comment by HelenaSabel** [comment] 2015-10-05 02:12
Oops, sorry! I keep forgetting about that! Thank you for noticing and
fixing it!
Em 05/10/2015 01:30, "Elisa Beshero-Bondar" notifications@github.com
escreveu:

**Comment by ebeshero** [comment] 2015-10-26 10:38
@HelenaSabel I'm just reviewing our Issues board, and I've been discussing this particular issue with @setriplette. We think we should exclude Southey's notes from the word counts and when processing Southey's additions, since the notes are meta-comments on the text. Have you been doing this in the XSLT for producing the tables? (I can take a look later, but you will know instantly!) 

I wonder for the tables if we can simply locate the note elements, do a word count inside them, and just subtract those words from the total counts. In your processing of quantities of that Southey has added, those are just based on counts of the anchor elements themselves, I think, and not based on word counts--so perhaps this is something we can deal with quickly and easily. Let me know!

**Comment by HelenaSabel** [comment] 2015-10-26 10:49
I dealt with the notes as if they were a regular addition, but that's easy to fix. So what I should do now is to not process them, so they are not taken into account for the statistics. My question is, do you want them in the alignment charts? maybe as a mouse-over tooltip?

**Comment by ebeshero** [comment] 2015-10-26 11:35
@HelenaSabel Sure, but let's please not output Southey's notes as attribute values--I'd rather we not use tooltips for that reason--we'll lose formatting control, indicating where Southey uses italics for example--if we do that. My own mouseover notes are output inside span elements that I set to hide in CSS and that become visible via toggling an @class value with JavaScript on a mouse event. I can do that code if you like, or you can find it on the Mitford project letters or the Pacific project.

**Comment by HelenaSabel** [comment] 2015-10-26 11:51
Don't worry about it and consider it done! I'm glad to learn your preferences. I've begun to do the tooltips like that when I learnt about HTML @data attributes, and then do the styling with JavaScript, but I don't have any arguments to defend the use of @data over spans, so thank you for letting me know!

**Comment by ebeshero** [comment] 2015-10-26 12:23
Thanks, Helena. Southey's notes are sometimes pretty extensive, and they are something more than an informational label. They're really another level of text--what we call "paratext," as you've heard me discuss! :-)

**Comment by HelenaSabel** [comment] 2015-10-26 12:47
How about including the notes inside an `<anchor type="paratext" synch="#id">`?

**Comment by ebeshero** [comment] 2015-10-26 13:23
No--There is no need to develop a new tag for the notes. We only need anchor and milestone elements for self-closing markers to indicate points of correspondence and speech acts. Southey's notes are fully contained at the point where they are signaled, so we don't need self-closing elements--they sit inside unit s (sentence) elements within his text.

**Comment by ebeshero** [comment] 2015-10-26 13:51
Basically, the notes are never going to disrupt the XML hierarchy, and they are nested inside Southey's sentences (at the same level as a particular word in a sentence), so they are picked up and carried along with translation units in the main text that we synch to Montalvo, or mark as an addition to Montalvo. They are part of the mixed content of a unit Southey sentence.

**Comment by HelenaSabel** [comment] 2015-10-26 14:19
Ok! So just to be sure that everything is coded correctly (because I changed once @setriplette's stitchery adding an `<anchor type="add">` and it was wrong to consider it an addition), let me double-check with you. In the following sample,  the `<anchor ana="end"/>` is correctly located after the note, right?
`<anchor ana="start" synch="#M0_p1_c12"/>yet she would wed with none, but for her
                  solitary and holy life was commonly called the Lost Devotee <note anchored="true"
                     resp="#Southey">La Beata perdida. <hi rend="italic">Methodist, Puritan,</hi> or
                        <hi rend="italic">the Elect,</hi> would perhaps express the meaning of <hi
                        rend="italic">Beata,</hi> which is in common use, if they were not sectarian words.</note><anchor ana="end"/><anchor ana="start" synch="#M0_p1_c13"/>, because it was considered that for one of such rank,<anchor ana="end"/>`
And in this sample, where inside the note there are some Montalvo references, should I move the first `<anchor ana="end"/>` (the one before the note) to the very end (after "centered")?
`<anchor ana="start" synch="#M1_p1_c43"/>in whom as he beheld her by the light of the three torches, he thought all the beauty of the world was<anchor ana="end"/>
                  <note anchored="true" resp="#Southey">
                     <anchor ana="start" type="add"/>Here, says the Spanish author, we should learn,<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c52"/>that when women turn aside their thoughts from worldly things,<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c53"/>despising the great beauty with which Nature has endowed them,<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c54"/>the fresh youth which so much increases it,<anchor ana="end"/> 
                     <anchor ana="start" type="add"/>and<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c55"/>the delights and pleasures which with the riches of their parents they might hope to enjoy,<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c56"/>and chuse for the salvation of their souls to place themselves as recluses in poor habitations, and offer up with all obedience their own free will<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c57"/>to be subject to others, and pass their time without any of the pleasures or glories of the world,<anchor ana="end"/> 
                     <anchor ana="start" type="add"/>though<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c58"/>their sisters and kindred are enjoying them;<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c59"/>they ought with great earnestness to stop their ears,<anchor ana="end"/> 
                     <anchor ana="start" type="add"/>and<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c60"/>close their eyes,<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c61"/>and refuse to see friend or relation,<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c62"/>but retiring altogether to devout contemplation and holy prayer,<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c63"/>think them the true delights, as indeed they are;<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c64"/>lest by<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c65"/>seeing<anchor ana="end"/> 
                     <anchor ana="start" type="add"/>and hearing,<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c65"/>their religious purposes be overcome,<anchor ana="end"/> 
                     <anchor ana="start" type="add"/>and it<anchor ana="end"/> 
                     <anchor ana="start" synch="#M1_p1_c66"/>should be with them as it was with the Princess Elisena.<anchor ana="end"/>
                  </note> centered.</s>`

**Comment by ebeshero** [comment] 2015-10-26 18:53
Hmmm. Yes to the first case, but the second is complicated because of the stitchery inside the note (which I was not aware of until now, since it happened after my work with preparing the Southey text). We need to discuss this with Stacey. I think from the preliminary conversation I've had with her (in a car just now in the French countryside near the Chauvet Cave--Google for images)--we need a new category for "transposed translation" when Southey pushes a translated passage out of the main text and into the paratext of a note like this. More soon. But tell me--have we output information from the corresponding passages in this note in the tables do far? If not, we should... Because these passages aren't exactly omitted, and nor are they exactly included either!

More soon as Stacey and I discuss this. She says there is one other chapter with a note like this.

Thanks--stay tuned!
Elisa

**Comment by HelenaSabel** [comment] 2015-10-27 00:00
At this point, notes like the first example are not include either in the charts or the statistics, but the ones that have @synch attributes are (however, just by looking at the alignment table you wouldn't know that those alignments are done inside a note, but I'll change that tomorrow).
I didn't do the tooltips because I didn't know how to include that information in the feature structures charts. The problem is that `<string>` only allows you to have a string, so I can't include any elements inside Southey's or Montalvo's text to mark-up the notes (or the names). The only solution I could think of is to create the HTML charts using the original XML files, and forget about using feature structures as an intermediate to structure the information.

**Comment by HelenaSabel** [comment] 2015-10-27 00:47
If you open the Chapter2.html you can see the "transposed translations" in italics because it's late and I couldn't think of anything more elegant. There is a `@rendition="note"` attribute in the `<f>` that includes those notes, that I transformed to `@title="note"` (I chose `@title` because I was using `@class` for other information, but I can change it if you don't like it). 
Anyway, I bet you can find a better CSS solution for  `td[title]{font-style:italic}` (and maybe a more suitable color for `td.expansion{ color: #aba372}` since it's very hard to read). I think those are the most urgent things to change regarding the style of the alignment charts.

**Comment by ebeshero** [comment] 2015-10-27 02:08
@HelenaSabel We can and should keep using feature structures, and I'd really rather do that. We don't have to output it at all in HTML unless we decide we want it. The `<string>` element can be included inside any `<f>` element, and we can nest `<fs>` and `<f>` elements as deeply as we need to in order to bind any related information together. Here is an example from the TEI Guidelines: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/FS.html#FSST 

I really want to prioritize a strong foundation in the TEI here before even thinking about the presentation view in HTML.

**Comment by ebeshero** [comment] 2015-10-27 02:12
@HelenaSabel Please understand that the TEI is NOT an "intermediate" form in this project. It is a _fundamental_ form--a foundation for binding related kinds of information together, as XML should be. I realize that you are probably thinking I need help with creating HTML for display, but my highest priority right now is simply making sure we are able accurately to review and associate our data--before we output anything for presentation. I can take over the XSLT to feature structures output if this is getting to be too much--sorry. It's just important we discuss markup decisions like this before generating a lot of output.

**Comment by HelenaSabel** [comment] 2015-10-27 07:55
I understand perfectly, Elisa, and my wording wasn't very accurate when I talked about "intermediates" because I only meant for the HTML visualization (sorry). The problem is not the XSLT (as you can see in the folders, all the files are there), my doubt was how to deal with the notes inside Feature Structures. Can we walk through an example?
This is a sample of a feature structure (as they are structured at this point)
`<fs corresp="#M2_p1_c52">
               <f name="southey" n="9" ana="0.33">
                  <string>that
                  my art shows me  it is already done,</string>
               </f>
               <f name="montalvo" n="12">
                  <string>Sino tanto que mis suertes me muestran que es ya hecho:</string>
               </f>
               <f name="type" select="indefinite">
                  <string>Comments</string>
               </f>
            </fs>`
However, there is is a note inside Southey's text (the source document reads: `<anchor ana="start" synch="#M2_p1_c52"/>that
                  my art shows me <note anchored="true" resp="#Southey">mis suertes me
                     muestran.</note> it is already done,<anchor ana="end"/>`)
So the only way we can introduce the note is to do something like this:
`<f name="southey" n="9" ana="0.33">
                  <string>that
                  my art shows me</string><f name="note"><string>mis suertes me
                     muestran</string></f><f name="continuation"><string>it is already done,</string></f>`
What do you think?

**Comment by HelenaSabel** [comment] 2015-10-27 08:21
Well, maybe adding another `<f>` for the first part of the text would be more structured, so as not to create hierarchies that are not there:
`<f name="southey" n="9" ana="0.33"><f name="beginning">
                  <string>that
                  my art shows me</string></f><f name="note"><string>mis suertes me
                     muestran</string></f><f name="continuation"><string>it is already done,</string></f>`

**Comment by ebeshero** [comment] 2015-10-27 10:26
@HelenaSabel Yes, embedding the note as another `<f>` or even an internal `<fs>` makes sense, especially because we will have internal correspondences to Montalvo inside some of these notes. Also, I notice we can use the `@rend` attribute on `<string>` or on the other feature structure elements so we can even include Southey's italic pseudo markup of Spanish words.

**Comment by ebeshero** [comment] 2015-10-27 14:56
@HelenaSabel Just a quick note on timing: I'm prioritizing the Mitford visualization I need to make first for Friday's presentation. Our use of feature structures for analysis is something I'd like to highlight in the Amadis presentation on Saturday, snd whatever web visualization so we pull from that will be useful but also something we really are treating as preliminary since we don't have a lot of data yet and we're discussing our plans for developing the project and the kinds of things we are investigating. For our short-term and long-term purposes, a solid foundation in XML for later work seems most important. I don't know if we have time to reprocess things to remake the table of contents and its SVG charts--I can try reprocessing it if you're busy, but if you can do it over the next day or so, let me know! I am sorry about the time-crunch but as usual I am glad we are able to work out our disagreements over the code! I guess my work on annotations over multiple Southey projects means I really should have planned for this better!

**Comment by HelenaSabel** [comment] 2015-10-27 15:32
Let me update you on the materials we have because I don't think the table of contents need any changes (besides the styling and other "superficial" enhancement, like adding the links to the alignment charts or to a reading view of the text).
The SVG graphs contain, as we agreed, the proportion of the common text and the differences. Southey's notes are not taken into account for those graphs except when there is a direct correlation between the text of the note and Montalvo's text (so those are considered common text). Is there anything that you are afraid might be wrong?

I made some changes on the feature structures files (that I'll push as soon as possible but I made a mistake deleting some files, and now I pull but I don't recover those; I tried resetting to a previous commit but it's not working either, so as soon as I fix the git problems, I'll upload them).
So I'm going to copy here a few samples.
- Feature structure that contains matching text:
  `<fs corresp="#M2_p1_c1">
             <f name="southey" n="5" ana="1.6">
                <string ana="persName" corresp="#Perion">King
                   Perion</string>
                <string> having departed from</string>
             </f>
             <f name="montalvo" n="13">
                <string>Partido el rey Perión de la Pequeña Bretaña como ya se vos contó:</string>
             </f>
             <f name="type" select="indefinite">
                <string>Comments</string>
             </f>
          </fs>`
  Where @n contains the word number, @ana the relation between those numbers. The @ana inside the `<string>` was a way to get the personal and place names with a @corresp attribute to link later on to the SI contents. By @type="indefinite" attribute I meant that we haven't given any explanations to the type of matching.
- Feature structure that contains an addition by Southey:
  `<fs>
             <f name="southey" n="4">
                <string>they left the
                   Chapel,</string>
             </f>
             <f name="type" select="add">
                <string>Comments</string>
             </f>
          </fs>`
- Feature structure that contains a part of Montalvo's text not present in Southey (these are positioned between two matching clauses, so it's easy to read which part of the text Southey didn't include and why):
  `<fs corresp="M2_p1_c10 #M2_p1_c11 #M2_p1_c12 #M2_p1_c13 #M2_p1_c14 #M2_p1_c15">
             <f name="montalvo" n="49">
                <string>y muchas vezes eran sus coraçones atormentados: oyendo las grandes afrentas en armas que él se
                      ponía: temiendo de lo perder: y por esto desseavan todos tenerlo consigo: mas no lo podían acabar: que su fuerte coraçón no era contento sino cuando el
                      cuerpo ponía en los grandes peligros. </string>
             </f>
             <f name="type" select="omission">
                <string>Comments</string>
             </f>
          </fs>`
- Feature structure that contains a "regular" note inside a matching clause:
  `<fs corresp="#M2_p1_c52">
             <f name="southey" n="9" ana="0.33">
                <string>that
                my art shows me </string>
                <string ana="note" resp="#Southey">mis suertes me
                   muestran.</string>
                <string> it is already done,</string>
             </f>
             <f name="montalvo" n="12">
                <string>Sino tanto que mis suertes me muestran que es ya hecho:</string>
             </f>
             <f name="type" select="indefinite">
                <string>Comments</string>
             </f>
          </fs>`
  (as you can see, in the @ana is very close to 0 because the words inside the note are not included).
- Feature structures that include a note by Southey with matching text:
  `<fs>
             <f name="southey" n="8" rendition="note">
                <string>Here, says the Spanish author, we should learn,</string>
             </f>
             <f name="type" select="add">
                <string>Comments</string>
             </f>
          </fs>
          <fs corresp="#M1_p1_c52">
             <f name="southey" n="10" ana="0.2" rendition="note">
                <string>that when women turn aside their thoughts from worldly things,</string>
             </f>
             <f name="montalvo" n="12">
                <string>que assí como las mugeres apartando sus pensamientos de las mundales cosas:</string>
             </f>
             <f name="type" select="indefinite">
                <string>Comments</string>
             </f>
          </fs>
          <fs corresp="#M1_p1_c53">
             <f name="southey" n="10" ana="0" rendition="note">
                <string>despising the great beauty with which Nature has endowed them,</string>
             </f>
             <f name="montalvo" n="10">
                <string>despreciando la gran hermosura de que la natura las dotó:</string>
             </f>
             <f name="type" select="indefinite">
                <string>Comments</string>
             </f>
          </fs>
  `

**Comment by HelenaSabel** [comment] 2015-10-27 15:37
Do you think that the different `<string>` elements with @ana attributes is a good way to include the  elements that are nested inside the text? I could change it to `<f>` elements as we talked before. This was a way for me to check that I was able to retrieve the corresponding nodes correctly.

**Comment by ebeshero** [comment] 2015-10-27 15:57
@HelenaSabel Well, I was only thinking of @rend on the string elements for note text, and then reproducing the same f elements we use above the note level when we have applied markup to the notes. We are likely to make a special study of the note elements, to pull them out and look at them together. And we want to pull information from the notes about corresponding passages in Montalvo when we have marked them (especially where these differ from the referenced passages above the note level).  So as much as possible we should reproduce the same kinds of code for f elements that we use above the note level. It's interesting to think of the note as a layer within the translation!

**Comment by ebeshero** [comment] 2015-10-27 16:02
And I was only thinking of @rend to preserve Southey's italics, though I suppose that could be the realm of @ana, to designate highlighted non-English words. Better the informational markup all the way through. I think I might be on a mission lately against presentation markup for its own sake! ;-)

**Comment by ebeshero** [comment] 2015-10-27 16:07
@HelenaSabel ahh! Sorry to be reading these new messages backwards! I am only now reading your long post with sample new fs code...

**Comment by HelenaSabel** [comment] 2015-10-27 16:15
I could finally push the new fs files so you can browse those and it might be easier than the samples.

**Comment by ebeshero** [comment] 2015-10-27 16:21
@HelenaSabel Okay: I see what you're doing now. It's pretty elaborate! Here's a change I hope we can try that might simplify things a little:

An `<f>` element can contain an `<fs>` element, just like a list item can itself contain a new list. I had thought of Southey's notes (just as I do in other projects) as sitting inside the main text--a feature **within** a feature. So, my inclination is to process note elements in an embedded `<fs>` within a parent  `<f>` element. That way, we can continue using f elements to record correspondences and omissions where we have marked them inside notes, using @n and @ana for quantitative processing as you've been doing. 

I am not sure we need the record of persName and other SI references in feature structure markup, since it doesn't contribute to our analysis of the translation, does it? Can we leave that out to keep this more readable?

**Comment by HelenaSabel** [comment] 2015-10-27 16:36
Eliminating the SI references make the code way much simpler, so no problem there. Might I copy a modification of those samples to see if we are both picturing the same thing? (sorry for being so slow...).
- A note "embedded" inside a matching text:
  `<fs corresp="#M2_p1_c52"> <f name="southey" n="9" ana="0.33"><fs><f name="start"><string>that my art shows me</string></f><f name="note"><string>mis suertes me muestran.</string></f><f name="end"><string>it is already done,</string></f></fs></f> <f name="montalvo" n="12"> <string>Sino tanto que mis suertes me muestran que es ya hecho:</string> </f> <f name="type" select="indefinite"> <string>Comments</string> </f> </fs>`
- For the note that includes many correlated clauses (the last sample of the previous post) what about having a `<fs name="note">` that includes all the other `<fs>` as they are in that sample, but without the @rendition="note" attribute?

**Comment by ebeshero** [comment] 2015-10-27 17:37
Helena: What you say in your second bulleted example is what I had in mind--yes. The first one confuses me a little because I am not sure of the placement of the internal fs element--I want to take a closer look at it as soon as I am out of the car and can look at the TEI file on my computer, and also see where it is legal to position the fs. Can we try:

1) to give the inner fs an @name="note" wherever we have a note? and
2) to position the fs inside a string at exactly the point where the note appears in the text?

I am not sure if 2) will work, but I just want to see it and see if it makes sense to have it embedded in a string. It might not make the best sense--If it doesn't work, we can break the string, which is what I think you're doing here, and position the note in sequence...I need to open your file in oXygen to get a closer look! 

Excited to play with this...
--E

**Comment by ebeshero** [comment] 2015-10-27 17:54
What I'm considering now is that on one kind of output HTML table we can suppress notes when they don't contain translated material. But when they _do_ contain such material of interest, perhaps we can signal that, and hold that material in one of the following ways:
--either as a new set of table rows in the main table, or
--as something that expands on click from the table cell containing the note--perhaps an internal table within the cell(?) or perhaps something we output in a special way in its own table appearing next to the main table. 

I am not sure of the best layout for thus, but can we think about it together? We want to keep in mind that these tables, whether in TEI or viewed as HTML, are all for studying the translation "moves" that Southey has made. The movement of some translated passages to notes is one thing we now know is a kind of translation move worth tracking--so I am leaning toward treating notes in the main table rows, but I'm not sure...

E

**Comment by HelenaSabel** [comment] 2015-10-27 19:12
Hi, Elisa!
I still need to apply some of the changes we agreed today, so at this point the files don't look as they should. It's just a warning in case you browse them and wonder if I had misunderstood you :-) 
About he HTML output, the tables (Chapter1.html and so on) don't include the "regular" notes, but they do include those which have translated material. However, each row contains a matching clause, so if the same note has three anchors, you'll see the three consecutive rows. It's easy to guess that they belong to same note due to their position, but you shouldn't have to guess, right? Open Chapter2.html and look for the rows written in italics to see what I mean.

**Comment by ebeshero** [comment] 2015-10-27 22:15
Your Chapter2.html is wonderful, now that Stacey and I can finally look at it. Yay! The italicized notes stand out, but right, I wonder if there is a way to indicate that they belong all together, and I might have a solution here in nesting note features inside a passage of main text: What if we output such things in one table cell, with a nested table inside, and outlined that cell in red or something, in some way that tells us, "this content is all a bundle together, all part of a note"?

Thanks TREMENDOUSLY for your great energy today in working on this as we figured out what to do with the notes!

**Comment by HelenaSabel** [comment] 2015-10-28 12:37
I still need to work on this. The table inside of the cell was very hard to read because its content is quite big... 
Now the embedded notes are inside a span with CSS display:none value (in case you want to do something with them for the presentation. For the translated notes, I went back to the italics...

**Closed as completed** 2017-03-12 05:48 UTC
Labels: question
